version: '3.8'

services:
  apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    ports:
      - ${PROJECT_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../source:/var/www/html:rw,delegated
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - ../source:/var/www/html
    networks:
      - app-network

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mariadb
    networks:
      - app-network

  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge